name: No. of for in code changes

on:
  push:
    branches:
      - '**'

jobs:
  count-for:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: NO. of 'for's
        run: |
          python .github/scripts/count_for.py
