on:

name: No. of for in code changes

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  count-for:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Count 'for' and save output
        id: countfor
        run: |
          python .github/scripts/count_for.py > for_count.txt
      - name: Post result as PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('for_count.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
